export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";

export const GET_EMPTY = "GET_EMPTY";

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const GET_CURRENT_SUBJECT = "GET_CURRENT_SUBJECT";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const GET_ALL_TOPICS = "GET_ALL_TOPICS";
export const ADD_TOPIC = "ADD_TOPIC";
export const UPDATE_TOPIC = "UPDATE_TOPIC";
export const DELETE_TOPIC = "DELETE_TOPIC";
export const GET_CURRENT_TOPIC = "GET_CURRENT_TOPIC";

export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
export const DELETE_QUESTIONS = "DELETE_QUESTIONS";
export const GET_CURRENT_QUESTIONS = "GET_CURRENT_QUESTIONS";
export const TOTAL_QUESTIONS = "TOTAL_QUESTIONS";
export const GET_QUESTIONS_BY_SUBJECT = "GET_QUESTIONS_BY_SUBJECT";
export const GET_QUESTIONS_BY_SUBJECT_ID = "GET_QUESTIONS_BY_SUBJECT_ID";
export const GET_QUESTIONS_BY_TOPIC_ID = "GET_QUESTIONS_BY_TOPIC_ID";

// export const GET_PAPER_QUESTIONS_BY_PAPER = "GET_PAPER_QUESTIONS_BY_PAPER";

export const ADD_OPTION = "ADD_OPTION";

export const GET_ALL_PAPERS = "GET_ALL_PAPERS";
export const ADD_PAPER = "ADD_PAPER";
export const UPDATE_PAPER = "UPDATE_PAPER";
export const DELETE_PAPER = "DELETE_PAPER";
export const GET_CURRENT_PAPER = "GET_CURRENT_PAPERS";

export const GET_ALL_PAPER_QUESTIONS = "GET_ALL_PAPER_QUESTIONS";
export const ADD_PAPER_QUESTION = "ADD_PAPER_QUESTION";
export const UPDATE_PAPER_QUESTION = "UPDATE_PAPER_QUESTION";
export const DELETE_PAPER_QUESTION = "DELETE_PAPER_QUESTION";
export const GET_CURRENT_PAPER_QUESTION = "GET_CURRENT_PAPER_QUESTION";
export const GET_PAPER_QUESTIONS_BY_PAPER = "GET_PAPER_QUESTIONS_BY_PAPER";
export const GET_PAPER_QUESTIONS_BY_STUDENT_PAPER =
  "GET_PAPER_QUESTIONS_BY_STUDENT_PAPER";

export const GET_ALL_STUDENT_PAPERS = "GET_ALL_STUDENT_PAPERS";
export const ADD_STUDENT_PAPER = "ADD_STUDENT_PAPER";
export const UPDATE_STUDENT_PAPER = "UPDATE_STUDENT_PAPER";
export const DELETE_STUDENT_PAPER = "DELETE_STUDENT_PAPER";
export const GET_CURRENT_STUDENT_PAPER = "GET_CURRENT_STUDENT_PAPER";
export const PATCH_STUDENT_PAPER = "PATCH_STUDENT_PAPER";
export const GET_RESULT = "GET_RESULT";

export const GET_ALL_OPTIONS = "GET_ALL_OPTIONS";
export const ADD_OPTIONS = "ADD_OPTIONS";
export const UPDATE_OPTIONS = "UPDATE_OPTIONS";
export const DELETE_OPTIONS = "DELETE_OPTIONS";
export const GET_CURRENT_OPTION = "GET_CURRENT_OPTION";

export const GET_ALL_STUDENT_ANSWER = "GET_ALL_STUDENT_ANSWER";
export const ADD_ARRAY_OF_STUDENT_ANSWER = "ADD_ARRAY_OF_STUDENT_ANSWER";
